invoice-master/invoice-master/Invoice_Management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('invoiceapp.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

invoice-master/invoice-master/invoiceapp/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from invoiceapp.views import (InvoiceView, invoice_cancel_view, InvoiceUpdateView, client_cancel_view,
                              CompanyListView, CompanyUpdateView, company_cancel_view, ClientListView, CompanySetup,
                              get_all_addresses, delete_particulars, delete_address, delete_bank, ReportListView,
                              ClientSetup, ClientUpdateView, generate_preview_invoice, InvoiceDetailView,
                              update_payment_status, get_sub_unit)
from invoiceapp.views.common import generate_preview_invoice_temp2

urlpatterns = [
    path('', login_required(CompanyListView.as_view(), login_url='/accounts/login'), name="company-basic"),
    path('company/<pk>/update', login_required(CompanyUpdateView.as_view(), login_url='/accounts/login'),
         name="company-update"),
    path('company/<pk>/cancel', login_required(company_cancel_view, login_url='/accounts/login'),
         name="company-delete"),
    path('company/', login_required(CompanySetup.as_view(), login_url='/accounts/login'), name="company-setup"),

    path('address/<pk>/delete', login_required(delete_address, login_url='/accounts/login'), name="delete-address"),
    path('bank/<pk>/delete', login_required(delete_bank, login_url='/accounts/login'), name="delete-bank"),

    path('clients/', login_required(ClientListView.as_view(), login_url='/accounts/login'), name="client-list"),

    path('client/<pk>/update', login_required(ClientUpdateView.as_view(), login_url='/accounts/login'),
         name="client-update"),
    path('client/<pk>/cancel', login_required(client_cancel_view, login_url='/accounts/login'), name="client-cancel"),

    path('client/', login_required(ClientSetup.as_view(), login_url='/accounts/login'), name="client-setup"),

    path('invoice/', login_required(InvoiceView.as_view(), login_url='/accounts/login'), name="invoice"),
    path('invoices/', login_required(ReportListView, login_url='/accounts/login'), name="invoice-list"),
    path('invoice/<pk>/update', login_required(InvoiceUpdateView.as_view(), login_url='/accounts/login'),
         name="invoice-update"),

    path('invoice/<pk>/cancel', login_required(invoice_cancel_view, login_url='/accounts/login'),name="invoice-cancel"),

   
    path('invoice/<pk>/update-status', login_required(update_payment_status, login_url='/accounts/login'),
         name="invoice-update-status"),


    path('particulars/<pk>/delete', login_required(delete_particulars, login_url='/accounts/login'),
         name="particulars-delete"),
    path('client-address/<pk>', login_required(get_all_addresses, login_url='/accounts/login'), name="client-address"),

    path('invoice-preview/<pk>', login_required(InvoiceDetailView.as_view(), login_url='/accounts/login'),
         name="invoice-preview-fixed"),
    path('invoice-preview/', login_required(generate_preview_invoice, login_url='/accounts/login'),
         name="invoice-preview"),
    path('invoice-preview-temp2/', login_required(generate_preview_invoice_temp2, login_url='/accounts/login'),
         name="invoice-preview-temp2"),
    path('currency/<pk>', login_required(get_sub_unit, login_url='/accounts/login'), name='currency'),
]

invoice-master/invoice-master/invoiceapp/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.db.models import Sum

# Create your models here.

PROJECT_TYPE = (
    ('fixed price', 'Fixed Price'),
    ('hourly', 'Hourly'),
)

ACCOUNT_TYPE = (
    ('inr', 'INR'),
    ('usd', 'USD'),
    ('gbp', 'GBP'),
    ('aud', 'AUD'),
)

PAYMENT_STATUS = (
    ('Pending', 'Pending'),
    ('Paid', 'Paid')
)


class BankAccountType(models.Model):
    type = models.CharField(max_length=120)

    def __str__(self):
        return self.type


class AccountCurency(models.Model):
    cuurency = models.CharField(max_length=120)

    def __str__(self):
        return self.cuurency


class Currency(models.Model):
    # Enter html code if unable to enter sign in symbol
    symbol = models.CharField(max_length=5, null=True, blank=True)
    currency = models.CharField(max_length=120)
    currency_unit = models.CharField(max_length=120)
    sub_unit = models.CharField(max_length=120)

    def __str__(self):
        return self.currency


class ResourceType(models.Model):
    resource_type_name = models.CharField(max_length=120)

    def __str__(self):
        return self.resource_type_name


# ********************************************

class Company(models.Model):
    status = models.BooleanField(default=True, null=True, blank=True)
    logo = models.ImageField(blank=True, default='company.png',
                             upload_to='logo', null=True)
    name = models.CharField(max_length=50)
    website = models.CharField(max_length=50, blank=True, null=True)
    phone_no = models.CharField(max_length=12, null=True, blank=True)
    email_id = models.EmailField(max_length=50, null=True, blank=True)
    invoice_initial = models.CharField(max_length=50, default='SYS-INV')
    cin = models.CharField(max_length=50, null=True, blank=True)
    # eefc_account = models.CharField(max_length=30, null=True, blank=True)
    invoice_count = models.IntegerField(default=00000, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.name


class CompanyAdditionalInfo(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True,
                                null=True)
    company_pan_no = models.CharField(max_length=20, blank=True, null=True)
    gstn = models.CharField(max_length=100, blank=True, null=True)
    iec = models.CharField(max_length=100, blank=True, null=True)
    lut_bond = RichTextField(blank=True, null=True)
    terms_condition = RichTextField(blank=True, null=True)
    self_declaration = RichTextField(blank=True, null=True)

    def __str__(self):
        return self.company.name


class CompanyBankDetail(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True,
                                null=True)
    account_number = models.CharField(max_length=20, blank=True, null=True)
    account_type = models.ForeignKey(BankAccountType, on_delete=models.CASCADE,
                                     blank=True, null=True)
    ifsc_code = models.CharField(max_length=50, blank=True, null=True)
    bank_ad_code = models.CharField(max_length=50, blank=True, null=True)
    bank_address = models.CharField(max_length=250, null=True, blank=True)
    name = models.CharField(max_length=50, null=True, blank=True)
    branch_code = models.CharField(max_length=20, null=True, blank=True)
    eefc_account = models.CharField(max_length=30, null=True, blank=True)
    account_currency = models.ForeignKey(AccountCurency,
                                         on_delete=models.CASCADE, blank=True,
                                         null=True)

    def __str__(self):
        return "{0}-{1}".format(self.account_number, self.name)


class Project(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Client(models.Model):
    status = models.BooleanField(default=True, null=True, blank=True)
    logo = models.ImageField(blank=True, default='client.png', upload_to='logo',
                             null=True)
    name = models.CharField(max_length=50)
    phone_no = models.CharField(max_length=12, null=True, blank=True)
    email_id = models.EmailField(max_length=50, null=True, blank=True)
    website = models.CharField(max_length=50, blank=True, null=True)
    pan = models.CharField(max_length=50, blank=True, null=True)
    gstn = models.CharField(max_length=50, blank=True, null=True)
    iec = models.CharField(max_length=50, blank=True, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True,
                                null=True)
    project_type = models.CharField(max_length=50, choices=PROJECT_TYPE,
                                    blank=True, null=True)
    agreement_detail = RichTextField(blank=True, null=True)
    agreement_date = models.DateField(blank=True, null=True)
    agreement = models.FileField(upload_to='agreementfile/', blank=True,
                                 null=True)

    def __str__(self):
        return self.name


class Address(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True,
                                blank=True, default=None,
                                related_name="company")
    client = models.ForeignKey(Client, on_delete=models.CASCADE, null=True,
                               blank=True, default=None, related_name="client")
    address = models.CharField(max_length=300)
    zip_code = models.CharField(max_length=50, null=True, blank=True)
    street = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.address


class Developer(models.Model):
    name = models.CharField(max_length=50)
    phone_no = models.CharField(max_length=12, null=True, blank=True)
    email_id = models.EmailField(max_length=50, null=True, blank=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True,
                                blank=True)
    project_type = models.CharField(max_length=50, choices=PROJECT_TYPE,
                                    default='hourly')
    resource_type = models.ForeignKey(ResourceType, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Invoice(models.Model):
    from_address = models.ForeignKey(Address, on_delete=models.CASCADE,
                                     related_name='company_address', null=True,
                                     blank=True)
    from_address_text = models.TextField(null=True, blank=True)
    website = models.CharField(max_length=120, null=True, blank=True)
    to_address_text = models.TextField(null=True, blank=True)
    to_address = models.ForeignKey(Address, on_delete=models.CASCADE,
                                   related_name='client_address', null=True,
                                   blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True,
                                blank=True)
    company_name = models.CharField(max_length=120)
    company_bank = models.ForeignKey(CompanyBankDetail,
                                     on_delete=models.CASCADE, null=True,
                                     blank=True)
    company_bank_add_text = models.CharField(max_length=300, null=True,
                                             blank=True)
    company_bank_acc_text = models.CharField(max_length=20, null=True,
                                             blank=True)
    company_bank_ifsc_text = models.CharField(max_length=20, null=True,
                                              blank=True)
    company_bank_acc_type_text = models.CharField(max_length=30, null=True,
                                                  blank=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, null=True,
                               blank=True)
    client_name = models.CharField(max_length=120)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True,
                                blank=True)
    invoice_number = models.CharField(max_length=50)
    project_name = models.CharField(max_length=120, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    phone_no = models.CharField(max_length=15, null=True, blank=True)
    agreement_date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    exchange_rate = models.DecimalField(max_digits=8, decimal_places=2,
                                        default=1)
    total_amount = models.DecimalField(max_digits=13, decimal_places=2)
    currency_name = models.CharField(max_length=32, null=True, blank=True)
    currency_symbol = models.CharField(max_length=10, null=True, blank=True)
    name_of_person = models.CharField(max_length=60, null=True, blank=True)
    bank_name = models.CharField(max_length=50, null=True, blank=True)
    bank_ad_code = models.CharField(max_length=20, null=True, blank=True)
    company_pan_no = models.CharField(max_length=15, null=True, blank=True)
    company_iec = models.CharField(max_length=15, null=True, blank=True)
    company_lut_bond = RichTextField(null=True, blank=True)
    company_terms_condition = RichTextField(null=True, blank=True)
    company_self_declaration = RichTextField(null=True, blank=True)
    company_cin = models.CharField(max_length=50, null=True, blank=True)
    company_eefc = models.CharField(max_length=50, null=True, blank=True)
    branch_code = models.CharField(max_length=20, null=True, blank=True)
    payment_status = models.CharField(choices=PAYMENT_STATUS, max_length=20,
                                      default="pending")
    project_type = models.CharField(max_length=50, choices=PROJECT_TYPE,
                                    default='hourly')
    cgst = models.DecimalField(max_digits=8, decimal_places=2, null=True,

invoice-master/invoice-master/invoiceapp/views/django_filters.py
import django_filters
from invoiceapp.models import Invoice


class ReportFilter(django_filters.FilterSet):
    OPTIONS = (("Pending", 'Pending'), ("Paid", 'Paid'))
    payment_status = django_filters.ChoiceFilter(empty_label='Select Status', label="Invoice Status",
                                                 choices=OPTIONS)

    created_at = django_filters.DateFromToRangeFilter()

    class Meta:
        model = Invoice
        fields = {'payment_status', 'project', 'project_name', 'client', 'created_at'}

    def __init__(self, *args, **kwargs):
        super(ReportFilter, self).__init__(*args, **kwargs)
        self.filters['project'].label = 'Project'
        self.filters['client'].lable = 'Select Client'
        self.filters['created_at'].label = 'Date Range'
        self.form.fields['project'].empty_label = 'Select Project'
        self.form.fields['client'].empty_label = 'Select Client'

invoice-master/invoice-master/invoiceapp/views/particulars.py
import json
from django.http import HttpResponse
from invoiceapp.models import Particular


def delete_particulars(request, pk):
    if request.method == 'POST':
        Particular.objects.get(pk=pk).delete()
    return HttpResponse(json.dumps({"message": "successfully deleted"}))

invoice-master/invoice-master/invoiceapp/templates/client_setup.html
{% extends "main_base.html" %}

{% load static %}
{% get_media_prefix as MEDIA_URL %}
{% block content %}

<script src="{% static 'js/formset.js' %}"></script>
<script src="{% static 'js/formset_address.js' %}"></script>
    <script src="{% static 'js/form_validation.js' %}"></script>
 <script>
         $(function() {
            $( "#id_agreement_date" ).datepicker();
         });
      </script>
  <form id="msform" method="POST" enctype="multipart/form-data" action="">
    {% csrf_token %}
   <a class="btn btn-primary btn-rounded float-right" href="{% url "client-list" %}" role="button">Back To List</a>

    <br> <br>
    
    <div class="row">
        {% csrf_token %}
      <div class="col-md-12 custom-tabs">
        <nav>
          <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
              <a class="nav-item_ nav-link active" id="nav-home-tab" data-toggle="" href="#nav-basic" role="tab" aria-controls="nav-home" aria-selected="true">
                Basic Information
              </a>
              <a class="nav-item_ nav-link" id="nav-profile-tab" data-toggle="" href="#nav-additional" role="tab" aria-controls="nav-profile" aria-selected="false">
                Aditional Information
              </a>
            </div>
        </nav>
        <div class="tab-content py-3 px-3 px-sm-0" id="nav-tabContent">
          <div class="tab-pane fade show active" id="nav-basic" role="tabpanel" aria-labelledby="nav-home-tab"> 
           {% if form.errors %}
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ field.name }}: {{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ field.name }}: {{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% if form2.errors %}
                            {% for field in form2 %}
                                {% for error in field.errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ field.name }}: {{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ field.name }}: {{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endif %}


            <div class="row">
              <div class="form-group col-xl-4 col-md-4 col-lg-4">
               <!--  <input type="file" name="logo" accept="image/*" id="id_logo"> -->
              
                 {%  if is_edit %}
            {% if client.logo %}
            <img src="{{ client.logo.url }}" class="rounded" width="40px;"  height="40px;">
                {% endif %}
                 {{form.logo}} 
                          
                      {% else %}
                     <label style=" font-style: monospace; opacity: 0.7;"> Add Client Logo </label>
                     {{form.logo}}

                    {% endif %}
                



              </div>
                
            </div>
            <div class="row">
                <div class="form-group col-xl-4 col-md-4 col-lg-4">
                  <!-- <input class="form-control" placeholder="Enter Client name *" type="text" name="client_name" maxlength="50" required="" id="id_client_name" value=""> -->
                    <label style=" font-style: monospace; opacity: 0.7;"> Enter Client Name* </label>
                  {{form.name}}
                </div>
                <div class="form-group col-xl-4 col-md-4 col-lg-4">
                  <!-- <input class="form-control" placeholder="Wesite *" type="text" name="website" maxlength="50" required="" id="id_website" value=""> -->
                   <label style=" font-style: monospace; opacity: 0.7;"> Website </label>
                  {{form.website}}
                </div>
              <div class="form-group col-xl-4 col-md-4 col-lg-4">
                  <!-- <input class="form-control" placeholder="Wesite *" type="text" name="website" maxlength="50" required="" id="id_website" value=""> -->
                  <label style=" font-style: monospace; opacity: 0.7;"> Phone No </label>
                  {{form.phone_no}}
                </div>
            </div>
            <div class="row">
              <div class="form-group col-xl-4 col-md-4 col-lg-4">
                <!-- <input class="form-control" placeholder="Wesite *" type="text" name="website" maxlength="50" required="" id="id_website" value=""> -->
                 <label style=" font-style: monospace; opacity: 0.7;"> Email Id  </label>
                {{form.email_id}}
              </div>
            </div>
            {{ form2.management_form }}
            {% for form1 in form2 %}
              
              <div class="address-row">
                <div class="row">
                  <div class="form-group col-xl-4 col-md-4 col-lg-4">
                    <label style=" font-style: monospace; opacity: 0.7;"> Zip Code </label>
                    {{form1.zip_code}}
                     {{form1.id}}
                  </div>
                  <div class="form-group col-xl-4 col-md-4 col-lg-4">
                    <label style=" font-style: monospace; opacity: 0.7;"> Client Address* </label>
                    {{form1.address}}
                  </div>
                  <div class="form-group col-xl-4 col-md-4 col-lg-4">
                      <label style=" font-style: monospace; opacity: 0.7;"> Street </label>
                    {{form1.street}}
                  </div>
                </div>


                <div class="row">
                  <div class="form-group col-xl-4 col-md-4 col-lg-4 input-group-append">
                    {%  if is_edit %}
                      <button class="btn btn-danger btn-rounded remove-address"> Remove</button>
                    {% else %}
                      <button class="btn btn-primary btn-rounded add-address">Add Another Address (*)</button>
                    {% endif %}
                  </div>
                </div>
              </div>


            {% endfor %}
             {%  if is_edit %}
                     
                      <button class="btn btn-primary btn-rounded add-address">Add Another Address (*)</button>
                    {% endif %}
            <a class="btn btn-secondary btn-rounded float-right mr-2" href="{% url "client-list" %}" role="button">Cancel</a> 
            <button class="btn btn-primary btn-rounded next action-button float-right mr-2" name="next" value="Next" type="button">Next</button>

          </div>
          <div class="tab-pane fade " id="nav-additional" role="tabpanel" aria-labelledby="nav-profile-tab">
            <div class="page-header">
              <h1 class="page-title"></h1>
                {{ form.media }}
            </div>

            <div class="row">
              <div class="form-group col-xl-4 col-md-4 col-lg-4">
                <!-- <input class="form-control" placeholder="Client PAN No. *" type="text" name="pan" maxlength="50" required="" id="id_pan" value=""> -->
                 <label style=" font-style: monospace; opacity: 0.7;"> Client Pan No </label>
                {{form.pan}}
              </div>
              <div class="form-group col-xl-4 col-md-4 col-lg-4">
               <!--  <input class="form-control" placeholder="GSTN *" type="text" name="gstn" maxlength="50" required="" id="id_gstn" value=""> -->
                <label style=" font-style: monospace; opacity: 0.7;"> Gstn </label>
                {{form.gstn}}
              </div>
              <div class="form-group col-xl-4 col-md-4 col-lg-4">
                <!-- <input class="form-control" placeholder="IEC" type="text" name="iec" maxlength="50" id="id_iec" value=""> -->
                  <label style=" font-style: monospace; opacity: 0.7;"> Iec </label>
                 {{form.iec}}
              </div>
            </div>


            <div class="row">
              <div class="form-group col-xl-6 col-md-6 col-lg-6">
                <!-- <select class="form-control" name="project" id="id_project">
                  <option value="" selected="selected">Project name</option>
                </select> -->

                <label style=" font-style: monospace; opacity: 0.7;"> Project </label>

                {{form.project}}

              </div>
              <div class="form-group col-xl-6 col-md-6 col-lg-6">
                <label style=" font-style: monospace; opacity: 0.7;"> Project Type</label>
                  {{form.project_type}}
              </div>
            </div>

            <div class="row">
              <div class="form-group col-xl-2 col-md-2 col-lg-2">
               <!--  <textarea class="form-control" rows="3" id="id_agreement_detail" name="agreement_detail" placeholder="Agreement details" value=""></textarea> -->
               <!--  {{form.agreement_detail.label}}: -->
                <label style=" font-style: monospace; opacity: 0.7;"> Agreement Detail </label>
             
               
              </div>
                <div class="form-group col-xl-10 col-md-10 col-lg-10">
               <!--  <textarea class="form-control" rows="3" id="id_agreement_detail" name="agreement_detail" placeholder="Agreement details" value=""></textarea> -->

                {{form.agreement_detail}} 

              </div>
            </div>
            <div class="row">
              <div class="form-group col-xl-6 col-md-6 col-lg-6">
               <!--  <input class="form-control" placeholder="Agreement Date" type="date" name="agreement_date" id="id_agreement_date" value=""> -->
                  <label style=" font-style: monospace; opacity: 0.7;"> Agreement Date </label>
                      {{form.agreement_date}}
              </div>
              <div class="form-group col-xl-6 col-md-6 col-lg-6">

                 <label style=" font-style: monospace; opacity: 0.7;"> Upload Copy Of Agreement </label>
                  {% if is_edit %}
                   <a href="{{ agreement }}">{{ form.agreement.value }}</a>

                  {% endif %}
                  {{form.agreement}}
              </div>
            </div>
            <a class="btn btn-secondary btn-rounded float-right mr-2" href="{% url "client-list" %}" role="button">Cancel</a>
            <button class="btn btn-primary btn-rounded next action-button float-right mr-2" name="next" value="Next" type="button">Submit</button>
            <button class="btn btn-primary btn-rounded previous float-right mr-2" name="previous" value="Previous" type="button">Previous</button>
            
              
          </div>
        </div>
      </div>
    </div>
  </form>

  <script>
    // Disable form submissions if there are invalid fields
    $(function() {
      'use strict';
      $(".previous").click(function (e) {
                var previous = $('#nav-tab a.active').prev()
                previous.length ?
                    $(previous).tab('show'):
                    $('#nav-tab a')[0].click();
            });
      $(".next").click(function(e){
        $("#msform").trigger('submit');
      });

      $("#msform").submit(function(e){
        e.preventDefault();
      }).validate({
        submitHandler: function(form) {
        var next = $('#nav-tab a.active').next()
          next.length?
          $(next).tab('show'):
          form.submit();
        }
      });
    });
  </script>
{% endblock %}

invoice-master/invoice-master/invoiceapp/templates/company.html
{% extends "main_base.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}"></script>

{% endblock %}
{% block content %}
<form id="msform" method="post" enctype="multipart/form-data">
	<!-- progressbar -->
	<ul id="progressbar">
		<li class="{% if step == 1 %} active{% endif %}"></li>
		<li class="{% if step == 2 %} active{% endif %}"></li>
        <li class="{%if page_name == 'home'%}active{% endif %}">

	</ul>
	<!-- fieldsets -->

	<fieldset style="{% if step == 1 %} display: block; {% else %} display: none; {% endif %}">
    {% csrf_token %}
   	    <table>
        {{ form }}
        </table>
        <input type="submit" name="next" class="next action-button" value="Next" />
	</fieldset>
	<fieldset style="{% if step == 2 %} display: block; {% else %} display: none; {% endif %}">
    <div style="text-align: justify; text-align-last: left;">
        Particulars/Item:
    </div>
    <div style="text-align: justify; text-align-last: right;">
        <a class="btn btn-success" href="{% url 'particulars'%}?next={{ request.path|urlencode }}?step=2">Create particular</a>
    </div>
    <table class="table table-striped">
    <tr>
         <th>Item Name</th>
         <th>Quantity</th>
         <th>Amount</th>
    </tr>
    {% for particular in particulars %}
        <tr>
            <td>{{ particular.resource_type.resource_type_name }}</td>
            <td>{{ particular.quantity }}</td>
            <td>{{ particular.amount }}</td>
            <td><a class="btn btn-warning" href="{% url 'particulars-update' particular.pk %}?next={{ request.path|urlencode }}?step=2">edit</a> |
                <a class="btn btn-danger" href="{% url 'particulars-delete' particular.pk %}?next={{ request.path|urlencode }}?step=2">delete</a></td>
        </tr>
    {% endfor %}
    </table>
		<input type="button" name="previous" class="previous action-button" value="Previous" />
		<input type="submit" name="Submit" class="next action-button" value="Submit" />
	</fieldset>

</form>
{% endblock %}

invoice-master/invoice-master/invoiceapp/templates/confirm_delete.html
{% extends "main_base.html" %}
{% block content %}

    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="post blog-post col-lg-8">
          <div class="container">
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <form method="post">
                {% csrf_token %}
                <input type="submit" value="Confirm">
            </form>
          </div>
        </main>

      </div>
    </div>

{% endblock %}